printWidth: 80
tabWidth: 4
useTabs: false
semi: true
singleQuote: false
jsxSingleQuote: false
quoteProps: "as-needed"
trailingComma: "es5"
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: "avoid"
endOfLine: "lf"
